services:
  - type: web
    name: app-database
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python seed.py
    env:
      DATABASE_URL: ${DATABASE_URI}
    startCommand: gunicorn app:app
