services:
  - type: web
    name: app-database
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade
      
      if [ ! -f .seeded ]; then
        python seed.py
        touch .seeded
      fi
    env:
      DATABASE_URL: ${DATABASE_URI}
    startCommand: gunicorn app:app
