services:
  - type: web
    name: app-database
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      flask db init
      flask db migrate
      flask db upgrade

      if [ ! -f .seeded ]; then
        python seed.py
        touch .seeded
      fi
    env:
      DATABASE_URL: ${DATABASE_URL}  # Ensure this is set correctly
      DB_PASSWORD: ${DB_PASSWORD}    # Ensure this is set correctly
    startCommand: gunicorn app:app
