"""Recreate initial migration

Revision ID: 0038dc89b65a
Revises: 
Create Date: 2024-05-20 12:07:03.052267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0038dc89b65a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_enrollments_course_id_courses')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_enrollments_student_id_students')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('student_course_associations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_course_associations',
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='fk_student_course_associations_course_id_courses'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='fk_student_course_associations_student_id_students'),
    sa.PrimaryKeyConstraint('student_id', 'course_id')
    )
    op.drop_table('enrollments')
    # ### end Alembic commands ###
