"""empty message

Revision ID: 0f89ce1e2e3d
Revises: d41fbf080679
Create Date: 2024-06-05 13:24:38.216857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f89ce1e2e3d'
down_revision = 'd41fbf080679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=2),
               existing_nullable=True)

    # ### end Alembic commands ###
